-- Phase 1 - Step 2: Relational and domain constraints
-- Target database: Oracle Database 21c
-- Prerequisite: run 01_schema.sql as the application owner.

SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
    IF SYS_CONTEXT('USERENV', 'SESSION_USER') IN ('SYS', 'SYSTEM') THEN
        RAISE_APPLICATION_ERROR(
            -20000,
            'Run application scripts as UNIVERSITY_APP, not SYS or SYSTEM.'
        );
    END IF;
END;
/

-- Unique constraints

ALTER TABLE UNITS ADD CONSTRAINT UQ_UNITS_NAME
    UNIQUE (UNIT_NAME);

ALTER TABLE STAFF ADD CONSTRAINT UQ_STAFF_ORACLE_USERNAME
    UNIQUE (ORACLE_USERNAME);

-- Required by the composite foreign key that guarantees a unit head belongs
-- to the same unit. STAFF_ID is already unique, but Oracle requires the exact
-- referenced column list to have a UNIQUE or PRIMARY KEY constraint.
ALTER TABLE STAFF ADD CONSTRAINT UQ_STAFF_ID_UNIT
    UNIQUE (STAFF_ID, UNIT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE STUDENTS ADD CONSTRAINT UQ_STUDENTS_ORACLE_USERNAME
    UNIQUE (ORACLE_USERNAME);

-- Domain constraints

ALTER TABLE STAFF ADD CONSTRAINT CK_STAFF_GENDER
    CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER'));

ALTER TABLE STAFF ADD CONSTRAINT CK_STAFF_ALLOWANCE
    CHECK (ALLOWANCE >= 0);

ALTER TABLE STAFF ADD CONSTRAINT CK_STAFF_ROLE
    CHECK (
        ROLE_CODE IN (
            'BASIC_STAFF',
            'LECTURER',
            'ACADEMIC_AFFAIRS',
            'UNIT_HEAD',
            'DEAN'
        )
    );

ALTER TABLE STAFF ADD CONSTRAINT CK_STAFF_CAMPUS
    CHECK (CAMPUS_ID IN ('CAMPUS_1', 'CAMPUS_2'));

ALTER TABLE STAFF ADD CONSTRAINT CK_STAFF_USERNAME
    CHECK (
        REGEXP_LIKE(
            ORACLE_USERNAME,
            '^[A-Z][A-Z0-9_$#]{0,127}$'
        )
    );

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_GENDER
    CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER'));

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_PROGRAM
    CHECK (
        PROGRAM_ID IN (
            'REGULAR',
            'HIGH_QUALITY',
            'ADVANCED',
            'VIETNAM_FRANCE'
        )
    );

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_MAJOR
    CHECK (MAJOR_ID IN ('IS', 'SE', 'CS', 'IT', 'CV', 'NET'));

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_CREDITS
    CHECK (ACCUMULATED_CREDITS BETWEEN 0 AND 300);

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_GPA
    CHECK (CUMULATIVE_GPA BETWEEN 0 AND 10);

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_CAMPUS
    CHECK (CAMPUS_ID IN ('CAMPUS_1', 'CAMPUS_2'));

ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_USERNAME
    CHECK (
        REGEXP_LIKE(
            ORACLE_USERNAME,
            '^[A-Z][A-Z0-9_$#]{0,127}$'
        )
    );

ALTER TABLE COURSES ADD CONSTRAINT CK_COURSES_CREDITS
    CHECK (CREDITS BETWEEN 1 AND 10);

ALTER TABLE COURSES ADD CONSTRAINT CK_COURSES_PERIODS
    CHECK (
        THEORY_PERIODS >= 0
        AND PRACTICE_PERIODS >= 0
        AND THEORY_PERIODS + PRACTICE_PERIODS > 0
    );

ALTER TABLE COURSES ADD CONSTRAINT CK_COURSES_MAX_STUDENTS
    CHECK (MAX_STUDENTS BETWEEN 1 AND 1000);

ALTER TABLE COURSE_PLANS ADD CONSTRAINT CK_COURSE_PLANS_SEMESTER
    CHECK (SEMESTER IN (1, 2, 3));

ALTER TABLE COURSE_PLANS ADD CONSTRAINT CK_COURSE_PLANS_YEAR
    CHECK (ACADEMIC_YEAR BETWEEN 2000 AND 9999);

ALTER TABLE COURSE_PLANS ADD CONSTRAINT CK_COURSE_PLANS_PROGRAM
    CHECK (
        PROGRAM_ID IN (
            'REGULAR',
            'HIGH_QUALITY',
            'ADVANCED',
            'VIETNAM_FRANCE'
        )
    );

-- Semester 1, 2, and 3 start on January 1, May 1, and September 1.
ALTER TABLE COURSE_PLANS ADD CONSTRAINT CK_COURSE_PLANS_START_DATE
    CHECK (
        EXTRACT(YEAR FROM START_DATE) = ACADEMIC_YEAR
        AND EXTRACT(DAY FROM START_DATE) = 1
        AND (
            (SEMESTER = 1 AND EXTRACT(MONTH FROM START_DATE) = 1)
            OR (SEMESTER = 2 AND EXTRACT(MONTH FROM START_DATE) = 5)
            OR (SEMESTER = 3 AND EXTRACT(MONTH FROM START_DATE) = 9)
        )
    );

ALTER TABLE TEACHING_ASSIGNMENTS
    ADD CONSTRAINT CK_ASSIGNMENTS_SEMESTER
    CHECK (SEMESTER IN (1, 2, 3));

ALTER TABLE TEACHING_ASSIGNMENTS
    ADD CONSTRAINT CK_ASSIGNMENTS_YEAR
    CHECK (ACADEMIC_YEAR BETWEEN 2000 AND 9999);

ALTER TABLE TEACHING_ASSIGNMENTS
    ADD CONSTRAINT CK_ASSIGNMENTS_PROGRAM
    CHECK (
        PROGRAM_ID IN (
            'REGULAR',
            'HIGH_QUALITY',
            'ADVANCED',
            'VIETNAM_FRANCE'
        )
    );

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_SEMESTER
    CHECK (SEMESTER IN (1, 2, 3));

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_YEAR
    CHECK (ACADEMIC_YEAR BETWEEN 2000 AND 9999);

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_PROGRAM
    CHECK (
        PROGRAM_ID IN (
            'REGULAR',
            'HIGH_QUALITY',
            'ADVANCED',
            'VIETNAM_FRANCE'
        )
    );

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_PRACTICE_SCORE
    CHECK (PRACTICE_SCORE BETWEEN 0 AND 10);

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_PROCESS_SCORE
    CHECK (PROCESS_SCORE BETWEEN 0 AND 10);

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_FINAL_EXAM
    CHECK (FINAL_EXAM_SCORE BETWEEN 0 AND 10);

ALTER TABLE ENROLLMENTS ADD CONSTRAINT CK_ENROLLMENTS_FINAL_SCORE
    CHECK (FINAL_SCORE BETWEEN 0 AND 10);

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT CK_NOTIFICATIONS_CREATED_BY
    CHECK (
        REGEXP_LIKE(
            CREATED_BY,
            '^[A-Z][A-Z0-9_$#]{0,127}$'
        )
    );

-- Relational constraints

-- The two deferred constraints below resolve the intentional cycle:
-- UNITS.HEAD_STAFF_ID -> STAFF and STAFF.UNIT_ID -> UNITS.
-- A unit and its first staff/head records must be created in one transaction.
ALTER TABLE STAFF ADD CONSTRAINT FK_STAFF_UNIT
    FOREIGN KEY (UNIT_ID)
    REFERENCES UNITS (UNIT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE UNITS MODIFY (HEAD_STAFF_ID NOT NULL);

ALTER TABLE UNITS ADD CONSTRAINT FK_UNITS_HEAD_IN_UNIT
    FOREIGN KEY (HEAD_STAFF_ID, UNIT_ID)
    REFERENCES STAFF (STAFF_ID, UNIT_ID)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE COURSES ADD CONSTRAINT FK_COURSES_UNIT
    FOREIGN KEY (UNIT_ID)
    REFERENCES UNITS (UNIT_ID);

ALTER TABLE COURSE_PLANS ADD CONSTRAINT FK_COURSE_PLANS_COURSE
    FOREIGN KEY (COURSE_ID)
    REFERENCES COURSES (COURSE_ID);

ALTER TABLE TEACHING_ASSIGNMENTS ADD CONSTRAINT FK_ASSIGNMENTS_LECTURER
    FOREIGN KEY (LECTURER_ID)
    REFERENCES STAFF (STAFF_ID);

ALTER TABLE TEACHING_ASSIGNMENTS ADD CONSTRAINT FK_ASSIGNMENTS_COURSE_PLAN
    FOREIGN KEY (
        COURSE_ID,
        SEMESTER,
        ACADEMIC_YEAR,
        PROGRAM_ID
    )
    REFERENCES COURSE_PLANS (
        COURSE_ID,
        SEMESTER,
        ACADEMIC_YEAR,
        PROGRAM_ID
    );

ALTER TABLE ENROLLMENTS ADD CONSTRAINT FK_ENROLLMENTS_STUDENT
    FOREIGN KEY (STUDENT_ID)
    REFERENCES STUDENTS (STUDENT_ID);

ALTER TABLE ENROLLMENTS ADD CONSTRAINT FK_ENROLLMENTS_ASSIGNMENT
    FOREIGN KEY (
        LECTURER_ID,
        COURSE_ID,
        SEMESTER,
        ACADEMIC_YEAR,
        PROGRAM_ID
    )
    REFERENCES TEACHING_ASSIGNMENTS (
        LECTURER_ID,
        COURSE_ID,
        SEMESTER,
        ACADEMIC_YEAR,
        PROGRAM_ID
    );

PROMPT Phase 1 - Step 2 completed: relational and domain constraints created.
