-- Phase 1 - Step 4A: Reference and security-policy test data
-- Target database: Oracle Database 21c
-- Run as the application owner after:
--   1. 01_schema.sql
--   2. 02_constraints.sql
--   3. 03_indexes.sql
--
-- This script assumes a clean schema created by 01_schema.sql.

SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
    IF SYS_CONTEXT('USERENV', 'SESSION_USER') IN ('SYS', 'SYSTEM') THEN
        RAISE_APPLICATION_ERROR(
            -20000,
            'Run application scripts as UNIVERSITY_APP, not SYS or SYSTEM.'
        );
    END IF;
END;
/

SET CONSTRAINTS ALL DEFERRED;

-- Units are inserted before staff. The deferred UNITS <-> STAFF constraints
-- are validated when this transaction commits.
INSERT ALL
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('OFFICE', 'Faculty Office', 'S0001')
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('IS', 'Information Systems', 'S0002')
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('SE', 'Software Engineering', 'S0003')
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('CS', 'Computer Science', 'S0004')
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('IT', 'Information Technology', 'S0005')
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('CV', 'Computer Vision', 'S0006')
    INTO UNITS (UNIT_ID, UNIT_NAME, HEAD_STAFF_ID)
        VALUES ('NET', 'Computer Networks and Telecommunications', 'S0007')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0001', 'Nguyen Van An', 'MALE', DATE '1975-03-12', 5000000,
        '0901000001', 'DEAN', 'OFFICE', 'DEAN01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0002', 'Tran Thi Binh', 'FEMALE', DATE '1980-07-21', 3000000,
        '0901000002', 'UNIT_HEAD', 'IS', 'HEAD_IS01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0003', 'Le Van Cuong', 'MALE', DATE '1979-11-08', 3000000,
        '0901000003', 'UNIT_HEAD', 'SE', 'HEAD_SE01', 'CAMPUS_2'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0004', 'Pham Thi Dung', 'FEMALE', DATE '1981-01-16', 3000000,
        '0901000004', 'UNIT_HEAD', 'CS', 'HEAD_CS01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0005', 'Hoang Van Giang', 'MALE', DATE '1978-05-25', 3000000,
        '0901000005', 'UNIT_HEAD', 'IT', 'HEAD_IT01', 'CAMPUS_2'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0006', 'Vo Thi Hoa', 'FEMALE', DATE '1982-09-19', 3000000,
        '0901000006', 'UNIT_HEAD', 'CV', 'HEAD_CV01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0007', 'Dang Van Khoa', 'MALE', DATE '1980-12-03', 3000000,
        '0901000007', 'UNIT_HEAD', 'NET', 'HEAD_NET01', 'CAMPUS_2'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0008', 'Bui Thi Lan', 'FEMALE', DATE '1990-02-14', 1000000,
        '0901000008', 'BASIC_STAFF', 'OFFICE', 'BASIC01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0009', 'Do Van Minh', 'MALE', DATE '1989-06-30', 1000000,
        '0901000009', 'BASIC_STAFF', 'IT', 'BASIC02', 'CAMPUS_2'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0010', 'Nguyen Thi Ngoc', 'FEMALE', DATE '1987-04-17', 2000000,
        '0901000010', 'LECTURER', 'IS', 'LECTURER01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0011', 'Tran Van Phuc', 'MALE', DATE '1986-08-09', 2000000,
        '0901000011', 'LECTURER', 'CS', 'LECTURER02', 'CAMPUS_2'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0012', 'Le Thi Quynh', 'FEMALE', DATE '1991-10-11', 1500000,
        '0901000012', 'ACADEMIC_AFFAIRS', 'OFFICE', 'AFFAIRS01', 'CAMPUS_1'
    )
    INTO STAFF (
        STAFF_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ALLOWANCE, PHONE,
        ROLE_CODE, UNIT_ID, ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'S0013', 'Pham Van Son', 'MALE', DATE '1992-01-23', 1500000,
        '0901000013', 'ACADEMIC_AFFAIRS', 'OFFICE', 'AFFAIRS02', 'CAMPUS_2'
    )
SELECT 1 FROM DUAL;

INSERT ALL
    INTO STUDENTS (
        STUDENT_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ADDRESS, PHONE,
        PROGRAM_ID, MAJOR_ID, ACCUMULATED_CREDITS, CUMULATIVE_GPA,
        ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'ST0001', 'Nguyen Minh Tam', 'MALE', DATE '2004-03-15',
        'District 1, Ho Chi Minh City', '0912000001', 'REGULAR', 'IS',
        60, 8.25, 'STUDENT01', 'CAMPUS_1'
    )
    INTO STUDENTS (
        STUDENT_ID, FULL_NAME, GENDER, DATE_OF_BIRTH, ADDRESS, PHONE,
        PROGRAM_ID, MAJOR_ID, ACCUMULATED_CREDITS, CUMULATIVE_GPA,
        ORACLE_USERNAME, CAMPUS_ID
    ) VALUES (
        'ST0002', 'Tran Gia Han', 'FEMALE', DATE '2004-09-02',
        'Thu Duc City, Ho Chi Minh City', '0912000002', 'REGULAR', 'CS',
        57, 7.80, 'STUDENT02', 'CAMPUS_2'
    )
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('GEN101', 'Introduction to University Studies', 2, 30, 0, 200, 'OFFICE')
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('IS101', 'Introduction to Information Systems', 3, 30, 30, 120, 'IS')
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('SE101', 'Introduction to Software Engineering', 3, 30, 30, 120, 'SE')
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('CS101', 'Data Structures and Algorithms', 4, 45, 30, 100, 'CS')
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('IT101', 'Information Technology Fundamentals', 3, 45, 15, 120, 'IT')
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('CV101', 'Introduction to Computer Vision', 3, 30, 30, 80, 'CV')
    INTO COURSES (
        COURSE_ID, COURSE_NAME, CREDITS, THEORY_PERIODS, PRACTICE_PERIODS,
        MAX_STUDENTS, UNIT_ID
    ) VALUES ('NET101', 'Computer Networks', 3, 30, 30, 100, 'NET')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('GEN101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('IS101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('SE101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('CS101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('IT101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('CV101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('NET101', 2, 2026, 'REGULAR', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('IS101', 2, 2026, 'HIGH_QUALITY', DATE '2026-05-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('IS101', 3, 2026, 'REGULAR', DATE '2026-09-01')
    INTO COURSE_PLANS (COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID, START_DATE)
        VALUES ('CS101', 3, 2026, 'REGULAR', DATE '2026-09-01')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0001', 'GEN101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0010', 'IS101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0003', 'SE101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0011', 'CS101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0005', 'IT101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0006', 'CV101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0007', 'NET101', 2, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0002', 'IS101', 2, 2026, 'HIGH_QUALITY')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0010', 'IS101', 3, 2026, 'REGULAR')
    INTO TEACHING_ASSIGNMENTS (
        LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR, PROGRAM_ID
    ) VALUES ('S0011', 'CS101', 3, 2026, 'REGULAR')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO ENROLLMENTS (
        STUDENT_ID, LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR,
        PROGRAM_ID, PRACTICE_SCORE, PROCESS_SCORE, FINAL_EXAM_SCORE, FINAL_SCORE
    ) VALUES (
        'ST0001', 'S0010', 'IS101', 2, 2026,
        'REGULAR', 8.50, 8.00, 7.50, 7.90
    )
    INTO ENROLLMENTS (
        STUDENT_ID, LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR,
        PROGRAM_ID, PRACTICE_SCORE, PROCESS_SCORE, FINAL_EXAM_SCORE, FINAL_SCORE
    ) VALUES (
        'ST0002', 'S0011', 'CS101', 2, 2026,
        'REGULAR', 7.50, 8.00, 7.00, 7.35
    )
    INTO ENROLLMENTS (
        STUDENT_ID, LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR,
        PROGRAM_ID, PRACTICE_SCORE, PROCESS_SCORE, FINAL_EXAM_SCORE, FINAL_SCORE
    ) VALUES (
        'ST0001', 'S0010', 'IS101', 3, 2026,
        'REGULAR', NULL, NULL, NULL, NULL
    )
    INTO ENROLLMENTS (
        STUDENT_ID, LECTURER_ID, COURSE_ID, SEMESTER, ACADEMIC_YEAR,
        PROGRAM_ID, PRACTICE_SCORE, PROCESS_SCORE, FINAL_EXAM_SCORE, FINAL_SCORE
    ) VALUES (
        'ST0002', 'S0011', 'CS101', 3, 2026,
        'REGULAR', NULL, NULL, NULL, NULL
    )
SELECT 1 FROM DUAL;

-- Use separate statements so the identity sequence advances once per row.
INSERT INTO NOTIFICATIONS (CONTENT, CREATED_BY)
VALUES ('T1 - Notification for all unit heads', 'DEAN01');

INSERT INTO NOTIFICATIONS (CONTENT, CREATED_BY)
VALUES ('T2 - Notification for IS students at Campus 1', 'AFFAIRS01');

INSERT INTO NOTIFICATIONS (CONTENT, CREATED_BY)
VALUES ('T3 - Notification for the CS unit head at Campus 1', 'DEAN01');

INSERT INTO NOTIFICATIONS (CONTENT, CREATED_BY)
VALUES ('T4 - Notification for CS unit heads at both campuses', 'DEAN01');

COMMIT;

PROMPT Phase 1 - Step 4A completed: reference and policy-test data inserted.
