--Select All Role--
CREATE OR REPLACE PROCEDURE ROLE_GET_AL(
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR 
      SELECT ROLE, AUTHENTICATION_TYPE, COMMON
      FROM DBA_ROLES;
END;
/