export const TEACHING_ASSIGNMENT_ROLES = [
  "LECTURER",
  "ACADEMIC_AFFAIRS",
  "UNIT_HEAD",
  "DEAN",
];

export const ENROLLMENT_ROLES = [
  "STUDENT",
  "LECTURER",
  "UNIT_HEAD",
  "DEAN",
];

export const SCORE_EDIT_ROLES = [
  "LECTURER",
  "UNIT_HEAD",
  "DEAN",
];

export const COURSE_PLAN_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const COURSE_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const STUDENT_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const UNIT_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const ASSIGNMENT_CREATE_DELETE_ROLES = ["UNIT_HEAD", "DEAN"];

export const ASSIGNMENT_UPDATE_ROLES = [
  "ACADEMIC_AFFAIRS",
  "UNIT_HEAD",
  "DEAN",
];

export const ENROLLMENT_MAINTENANCE_ROLES = ["ACADEMIC_AFFAIRS"];

export const DEAN_ROLES = ["DEAN"];

export const STAFF_ROLES = [
  "BASIC_STAFF",
  "LECTURER",
  "ACADEMIC_AFFAIRS",
  "UNIT_HEAD",
  "DEAN",
];
