export const TEACHING_ASSIGNMENT_ROLES = [
  "LECTURER",
  "ACADEMIC_AFFAIRS",
  "UNIT_HEAD",
  "DEAN",
];

export const ENROLLMENT_ROLES = [
  "STUDENT",
  "LECTURER",
  "UNIT_HEAD",
  "DEAN",
];

export const SCORE_EDIT_ROLES = [
  "LECTURER",
  "UNIT_HEAD",
  "DEAN",
];

export const COURSE_PLAN_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const COURSE_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const STUDENT_WRITE_ROLES = ["ACADEMIC_AFFAIRS"];

export const STAFF_ROLES = [
  "BASIC_STAFF",
  "LECTURER",
  "ACADEMIC_AFFAIRS",
  "UNIT_HEAD",
  "DEAN",
];
